# =========================
# MYSQL
# =========================
spring.datasource.url=jdbc:mysql://thomas.proxy.rlwy.net:27451/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=DeMPjmqGUzVQMMlEratoXKqxScQWhhVe
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# =========================
# REDIS
# =========================
spring.data.redis.host=redis.railway.internal
spring.data.redis.port=6379
spring.data.redis.username=default
spring.data.redis.password=wIgmTjjFTokvmJeohfdXVrZMjGjKhqKO
spring.data.redis.timeout=5000ms

# =========================
# JWT
# =========================
app.jwt.secret=deltaclause_secret_super_signature_2026_top1percent_longer_secret_needed_for_hmac_256
app.jwt.expiration-ms=864000000

# =========================
# SERVER
# =========================
server.port=${PORT:8080}